### ISSUE TITLE
Using custom dataset

### ISSUE THREAD

**Issue by Breinich** [felixleopoldo/benchpress#103]
I'm interested in running benchpress with my own dataset without a solution graph and I would like to use specifically notears and golem algorithms for research purposes.

I've set already this data configuration:

                "graph_id": null,

                "parameters_id": null,

                "data_id": "insilico.csv",

                "seed_range": null
                
but I don't know how should I configure the evaluation section to not let the config validator show an error of "ROC evaluation requires graph_id.".

I started from the gcastle.json configuration.

It can happen, that I'm missing something or not fully understand the environment, sorry in advance!

Thank you for your help!

**Comment by felixleopoldo** [comment]
Hi,
The evaluation metrics like TPR and FPR, etc. in the benchmarks module require a true DAG, that's why the module requires the true graph to be set. However, some outputs, like the timings and graph types, actually don't require the true graph. These should probably be somewhere else! Thanks for reminding me about this. 

What kind of output are you interested in? If you are interested in estimating the graphs, you should use the graph_plots module.

Hope this helps, otherwise let me know

**Comment by Breinich** [comment]
Yeah, I'm interesting in estimating the graphs and I was just wondering whether could it be possible to achieve this via running normally benchpress with a proper config.json file.

Thank you for your response and help very much!
