### ISSUE TITLE
Edges and non-edges

### ISSUE THREAD

**Issue by melmasri** [felixleopoldo/benchpress#51]
Hi @felixleopoldo 

it seems that the calculation of non-edges depend on the true skeleton, whether it allows self edges or not.  as shown in the following link

https://github.com/felixleopoldo/benchpress/blob/c5d96d6736b4869341414fec9f9a3459cfcf4525/workflow/rules/evaluation/benchmarks/run_summarise.R#L127

so it seems a better way to calculate total number of edges as `|V|(|V|-1)/2` and the deduct the existing edges. 

What do you think?

**Comment by felixleopoldo** [comment]
In general, it doesn't matter as long as it is correct. But I think the problem is also appearing in lines above 127 as well. Representing the undirected graphs `skel_true ` and `skel_est` as upper triangular matrices, by masking with `m = upper.tri(matrix(1, n_nodes, n_nodes))`  and using `m` instead of 1 in the equations on lines 122-127 might make it easier. Also `n_edges` should be called `P` and `n_nonedges` should be be called `N`.

**Comment by felixleopoldo** [comment]
Looking at it again, as self-loops should not exist, I think it is the 1s in 122-127 that is the problem. We could try masking with `m = upper.tri(matrix(1, n_nodes, n_nodes))` where `diag(m) = 0`.
